version: '3.8'

services:
  lio-mysql:
    restart: always
    image: mysql:8.0
    container_name: lio-mysql
    networks: 
      - sql-network
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: test321
      MYSQL_USER: dev2020
      MYSQL_PASSWORD: dev2020
      MYSQL_DATABASE: lioenix_db
      TZ: 'Asia/Shanghai'
    # command:
    #   -- max_allowed_packet=128M
    volumes: 
      - ./data/mysql/data:/var/lib/mysql

  lio-mongo:
    restart: always
    image: mongo:4.2.8
    container_name: lio-mongo
    networks: 
      - mongo-network
    ports: 
      - 27018:27017
    environment: 
      MONGO_INITDB_ROOT_PASSWORD: test321
      MONGO_INITDB_ROOT_USERNAME: root
      TZ: 'Asia/Shanghai'
    volumes: 
      - ./data/mongo/data:/data/db
    
  # lio-tomcat:
  #   restart: always
  #   image: tomcat:9
  #   container_name: lio-tomcat
  #   depends_on: 
  #     - lio-mysql
  #   networks: 
  #     - tomcat-network
  #   ports: 
  #     - 8181:8080
  #   volumes: 
  #     - ./webapp:/usr/local/tomcat/webapps
  #   environment:
  #     TZ: 'Asia/Shanghai'
  #     DATABASE_HOST: lio-mysql
  #     DATABASE_USER: dev2020
  #     DATABASE_PASSWORD: dev2020
  #     DATABASE_NAME: lioenix_db  
  #     DATABASE_PORT: 3306

  # lio-nginx:
  #   container_name: lio-nginx
  #   image: nginx:1.18
  #   restart: always
  #   ports:
  #   - 80:80
  #   - 4403:4403
  #   volumes:
  #   - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
     
networks:
  tomcat-network:
    name: tom-net
    driver: bridge
  sql-network:
    name: sql-net
    driver: bridge
  mongo-network:
    name: mongo-net
    driver: bridge
    